server:
  port: 80
  servlet:
    context-path: /cmfz
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_chuan_19-12-02
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: 192.168.64.10
    port: 6379
    database: 0
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
